.pre-commit-config.yaml
The alpha version, automatically provided to us by the pre-commit.ci bump, does not seem to actually work
=> Use non-alpha eslint pre-commit version

CONTRIBUTING.md
1. `pip install -e .` is needed, and will also do the initial JS / CSS build from https://github.com/yuvipanda/jupyterhub-fancy-profiles/pull/21
2. Add a note about `npm run webpack:watch` to rebuild changes
3. Use `python -m jupyterhub` to run jupyterhub, to minimize chances of venv shennanigans
Fixes #20
=> Add additional steps to CONTRIBUTING.md

MANIFEST.in
Without this, the built files are not included in the PyPI package
=> Include built files in sdist / wheels

jupyterhub_config.py, setupTests.js, src/ProfileForm.jsx, src/ProfileForm.test.js, src/form.css
Looks like this now:
Used to look like:
Changes:
1. Radio button is vertically centered in the profile
2. Profile display name is a `<h4>`, and the description (if present) is rendered as a `<p>`, instead of being in parantheses.
3. Small bottom border to differentiate between profiles
=> Update styling of profile display + description

jupyterhub_config.py, setupTests.js, src/ProfileForm.test.js, src/ResourceSelect.jsx, src/hooks/useSelectOptions.js
@oliverroick this got a bit hairy, but I think this was the simplest possible change I could think of to fix the issue and ensure the default handling is correct.
I added a profile list item to the test config, but am seeing some existing tests are failing with duplicate items on the page - which makes sense, but it might be good to get some help from you to fix @oliverroick 
@oliverroick maybe easiest to have a quick chat to walk through the fixes and you can maybe make suggestions for doing this better.
=> refs #38, fixes case where choices is empty but unlisted_choice is enabled

jupyterhub_config.py, setupTests.js, src/ProfileForm.jsx, src/ProfileForm.test.js, src/state.js
Fixes #39 
- Sets the default profile based on a `default: True` config in the jupyterhub_config
- Adds tests
@oliverroick there were a couple awkward things - leaving comments in the code, if you have any ideas.
Otherwise, I think this should work.
cc @yuvipanda
=> if a profile has default: true, select it by default, else select the first profile

src/ProfileForm.jsx, src/ProfileForm.test.js, src/form.css
Fixes #40 -
This feels a bit awful @oliverroick @yuvipanda 
This does (I think) replicate what the current kubespawner frontend does, where if the user clicks anywhere on a profile option, it selects the radio for that option.
I do think we should re-think these radio inputs for selection, and perhaps something like a more accordion-ish interface might make this a bit more obvious to the user.
I'm a bit worried that this makes it quite easy for a user to accidentally select a profile option when they didn't mean to, etc.
@yuvipanda if you get the time, could you test this and see if this is the behaviour you were hoping for?
For reference, this was the issue on `kubespawner` when we first implemented "unlisted_choice" about essentially the same thing: …
=> try onClick on whole profile to select

src/components/form/fields.jsx
Fixes #59
Adds the `name` attribute to `TextField` so the fields are included in form submission.
=> fix: Add name prop to TextField

package-lock.json, package.json, setupTests.js, src/ImageBuilder.jsx, src/ImageBuilder.test.js, src/form.css, src/hooks/useRefField.js, src/hooks/useRepositoryField.js
Contributes to #66: Extends the build-image form, so users can select a repository and branch, and add stronger validation for inputs.
Changes
- Adds a "Repository" field, which takes the repository for the image build.
- It can be provided either as `org/repo` or `github.com/org/repo` or `https://github.com/org/repo`. Other inputs should be rejected with an error. 
- The entered repo is further validated against the Github API. We're sending a `HEAD` request to verify if the repository exists and if it is public. 
- Adds a "Branch" field, allowing users to select the branch to build from. 
- The branch field will only be shown after the repository input has been verified.
- We're using the GitHub API to request a list of available branches, the select field is populated from the list of …
=> Add repo validation, enable branch selection

src/ImageBuilder.jsx, src/ProfileForm.jsx, src/ProfileForm.test.js, src/ProfileOptions.jsx, src/ResourceSelect.jsx, src/components/form/fields.jsx, src/form.css, src/hooks/useRefField.js, src/hooks/useRepositoryField.js, src/state.js, src/utils/index.js
Contributes to #66: Pre-select GitHub repo and GitHub branch when URL params are set
- The heavy lifting is done in `state.js` where we check for the presence of the URL parameters (`binderProvider`, `binderRepo`, `ref`), and set the selected profile to the one that supports dynamic image building. If more than one profile support dynamic image building, we show a warning and don't set the form fields.
- Validation of the Github repo string is still done in the back, but automatically executed when there is a default value (ie. the value from the `binderRepo` parameter.
=> Pre-select github repo and ref

src/form.css
=> Center labels on the profile form

src/ImageBuilder.jsx
Fixes #78 
All terminal instances had the same ID, which is why all output landed in the same window. We're using the field ID here, which itself is a combination of profile name and field name, to create unique terminal IDs.
=> Set unique IDs for terminal instances

src/hooks/useRefField.js, src/hooks/useRepositoryField.js
Fixes a small issue when initialising the image-builder form fields: If there's no default value, the field will be initialised with `undefined`, which is an anti-pattern. Fixing this by supplying an empty string if the `defaultValue` is `undefined`.
=> Initialise form values with empty string

src/ImageBuilder.jsx, src/ResourceSelect.jsx
Resolves #75 
Disabling the submit button proved tricky because of the way the form is architected. We don't have a global form state, so the `ProfileForm`, which renders the submit button, doesn't know about internals of `ImageBuilder. Instead, I added validation for the custom-field input and show an error if the field is not set.
=> Validate image-build before submit

src/ImageBuilder.jsx
Fixes #76 
- Adds new state `isBuildingImage`, which is used to set the `disabled` property of the build-image button
- ~Wraps the image-build state handling in a `Promise`, which we return from `buildImage`. This makes it easier in the `ImageBuilder` component to handle state updates, without having to pass callbacks to `buildImage`~
- Return Promises instead of using callback function, to make it easier in the `ImageBuilder` component to handle state updates
=> Disable build-image button while building

src/ProfileForm.jsx
The hitbox for what was selecting the profile was smaller without this change. With this change, we now match what the default kubespawner experience is.
Ref https://github.com/yuvipanda/jupyterhub-fancy-profiles/issues/40
=> Select profile even if the user clicks on the padding area

src/hooks/useSelectOptions.js
Fixes #84 
Fixes the boolean logic used to determine the default choice. Previously, the logic looked similar to
```
"a" || someVar > 1 ? "b" : "c"
```
which always results in "b" because it's evaluated like (see the parentheses): 
```
("a" || someVar > 1) ? "b" : "c"
```
By wrapping the `if` shorthand in parentheses, we make sure it's evaluated as "either a, or whatever the result of the `if` shorthand.
```
"a" || (someVar > 1 ? "b" : "c")
```
=> Ensure default choice is selected

src/ImageBuilder.jsx, src/components/form/fields.jsx, src/form.css
Resolves #92 
- Adds `hint` prop to `TextField` and the generic `Field` component. The hint is rendered only where there's no error on the field.
- Add `profile-option-control-hint` css class to style the hint
- Adapt spacing and font size of `profile-option-control-error` so it's in line with the new hint class
=> Add hint text for ref field

setupTests.js, src/ProfileForm.test.js, src/state.js
Resolves #95 
Adds test to support profiles where `profile_options` is and empty object, and where `profile_options`  is not present.
=> Add test for profiles without options

src/ImageBuilder.jsx
Resolves #55 
Specifies the colours in the Xterm theme. 
I checked all colours used with the [WebAIM contrast checker](https://webaim.org/resources/contrastchecker/) to ensure color/background combinations are accessible.
=> Specify terminal colors

src/ImageBuilder.tsx, src/ProfileForm.test.tsx, src/ProfileForm.tsx, src/components/form/Combobox.tsx, src/components/form/fields.tsx, src/form.css, src/state.tsx
Ref https://github.com/2i2c-org/jupyterhub-fancy-profiles/issues/111
Instead of greying out the submit button (which is hard, because we validate the form on submit, so we need to allow a submit to validate), I propose to display an error summary above the submit button. The summary contains a linked list of all errors in the form. Clicking on a link the list will scroll to the error.
/cc @wildintellect Would love to hear your thoughts on this solution.
=> Display error summary

src/ImageBuilder.tsx, src/components/form/Combobox.tsx
Ref [#62](https://github.com/2i2c-org/jupyterhub-fancy-profiles/issues/62)
Since the introduction of cached-value dropdowns, the originally reported error won't occur any more because we're intercepting the `keydown` event for all comboboxes, and handling the `Enter` input. 
In this PR, I'm adding changes so the image build does start if:
- The Enter key is pressed, and
- we're currently not focussing on the drop down
- all image-build related fields are valid
=> Start image build on Enter

setupTests.js, src/ImageBuilder.test.tsx, src/ImageBuilder.tsx, src/ProfileForm.test.tsx, src/ProfileForm.tsx, src/ResourceSelect.tsx, src/components/Permalink.tsx, src/context/Permalink.tsx, src/index.tsx, src/state.tsx, src/test/renderWithContext.tsx, src/types/config.ts, src/types/fields.ts
Resolves #109 Implements reading URL parameters and filling form.
Currently we're supporting:
- `profile` to select the profile
- `unlisted_choice` to fill the unlisted choice field in the profile
- `binderRepo`, `ref` and `binderProvider` to profile image-build options, which we already supported
- Plus, any key-value combination that is specified in the Jupytherhub config
To test, try the following:
- **Select image and resource** http://localhost:8000/hub/spawn?profile=gpu-only-usage&image=pangeo&resources=mem_10_8
- **Select custom docker image** http://localhost:8000/hub/spawn?profile=gpu-only-usage&image=unlisted_choice&resources=mem_10_8&unlisted_choice=my:image
- **Select build image and prefull repo parameters** http://localhost:8000/hub/spawn?profile=gpu-only-usage&image=--extra- …
=> Fill form from URL query parameters

src/components/form/CustomSelect.tsx
Fixes #128
Setting the maximum height for the select menu forces select to show a scrollbar of the items exceed the height.
=> Set select menu height

src/components/form/CustomSelect.tsx, src/form.css
Implements #129 
Adds dark mode styling for react-select components. I tried to use CSS vars as much as possible to align with the overall style of the site.
=> Fix darkmode styles for select
